<center>
    <h1>Top 5 Machine Learning Libraries in Python</h1>
    <h3>In this article we are going to learn about Numpy</h3>
</center>

## Numpy

__[NumPy](http://www.numpy.org/)__ is the fundamental package for scientific computing with Python. It mostly used for solving __matrix__ problems more specifically to solve __Linear Algebra__. When it comes to work with __arrays__ then __Numpy__ is a great choice.

### Creating a Numpy Array

In [1]:
import numpy as np

In [2]:
arr = np.array([])
type(arr)

numpy.ndarray

### Creating One Dimensional Array

In [3]:
one_d_array = np.array([1, 2, 3, 4, 5])

In [4]:
print(one_d_array)

[1 2 3 4 5]


In [5]:
# ndim attributes shows the number of dimension of an array
one_d_array.ndim  

1

In [6]:
# size attributes returns the size/length of the array
one_d_array.size

5

### Creating an array of zeros

In [7]:
np.zeros(5) # by default it produce float

array([0., 0., 0., 0., 0.])

In [8]:
# zeros() method takes another parameter for data type
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

### Creating a Sequence of Number

In [11]:
# first parameter denotes the starting point
# second paramter denotes the ending point
# if the third parameter was not specified then 1 is used as default
print(np.arange(1, 10))

[1 2 3 4 5 6 7 8 9]


In [12]:
print(np.arange(1, 10, 2))

[1 3 5 7 9]


In [44]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### Reshaping an Array

In [15]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### Flatten an Array

In [19]:
two_d_arr = np.arange(10).reshape(2, 5)
print(two_d_arr)
two_d_arr.ravel() 

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.arange(10).reshape(2, 5).T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [22]:
np.arange(10).reshape(2, 5).T.shape

(5, 2)

### Universal Functions

In [26]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
arr.max(), arr.min() # finding max, min

(9, 0)

In [30]:
np.exp(arr) # finding exponetial 

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [31]:
np.sqrt(arr) # finding square root

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

### Accessing and Iterating Arrays element

In [34]:
arr[5] # accessing the 6th element by index

5

In [35]:
for element in arr:
    print(element)

0
1
2
3
4
5
6
7
8
9


In [37]:
for element in arr:
    if(element % 2 == 0):
        print(element, "is positive")
    else:
        print(element, "is negative")

0 is positive
1 is negative
2 is positive
3 is negative
4 is positive
5 is negative
6 is positive
7 is negative
8 is positive
9 is negative


### Linear Algebra

In [40]:
_2d_arr = np.array([[10, 20], [30, 40]])
_2d_arr

array([[10, 20],
       [30, 40]])

In [41]:
_2d_arr.transpose() # transpose

array([[10, 30],
       [20, 40]])

In [44]:
%%time
np.linalg.inv(_2d_arr) # inverse

Wall time: 0 ns


array([[-0.2 ,  0.1 ],
       [ 0.15, -0.05]])

In [48]:
identity = np.eye(3, dtype=int) # 3x3 Identity matrix
identity

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [49]:
_2d_arr @ _2d_arr # matrix product

array([[ 700, 1000],
       [1500, 2200]])

In [50]:
np.trace(_2d_arr)  # trace

50

### Stacking

In [54]:
a = np.arange(0, 20, 2)
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [55]:
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
# vertical stacking
vs = np.vstack([a, b])
vs

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [57]:
# horizontal stacking
hs = np.hstack([a, b])
hs

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18,  0,  1,  2,  3,  4,  5,  6,
        7,  8,  9])