# Top 5 Machine Learning Libraries in Python
In this article we are going to learn about __Sci-kit__ Learn.

__Sci-kit__ learn is a library that provides a range of Supervised and Unsupervised Learning Algorithms. This library mainly focused on model building.

# An End to End Model using Sci-kit Learn:

In [5]:
# Firstly we need to import necessary libraries
import numpy as np
import pandas as pd

# Supervised Classification Learning Algorithms
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, auc, roc_curve

In [6]:
dataset = pd.read_csv(r"../dataset/student_result.csv")
print(dataset.head())

   math  bangla  english  result
0    70      80       90       1
1    30      40       50       0
2    50      20       35       0
3    80      33       33       1
4    33      35       36       1


In [7]:
X = dataset.drop("result", axis=1)
y = dataset["result"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state=1)

In [8]:
clf_lr = LogisticRegression()
pred_lr = clf_lr.fit(X_train, y_train).predict(X_test)

clf_knn = KNeighborsClassifier()
pred_knn = clf_knn.fit(X_train, y_train).predict(X_test)

clf_rf = RandomForestClassifier(random_state=1)
pred_rf = clf_rf.fit(X_train, y_train).predict(X_test)

clf_dt = DecisionTreeClassifier()
pred_dt = clf_dt.fit(X_train, y_train).predict(X_test)

In [9]:
print("Accuracy of Logistic Regression:", accuracy_score(pred_lr, y_test))
print("Accuracy of KNN:", accuracy_score(pred_knn, y_test))
print("Accuracy of Random Forest:", accuracy_score(pred_rf, y_test))
print("Accuracy of Decision Tree:", accuracy_score(pred_dt, y_test))

Accuracy of Logistic Regression: 0.8
Accuracy of KNN: 0.6
Accuracy of Random Forest: 0.8
Accuracy of Decision Tree: 0.8


In [10]:
print(classification_report(pred_lr, y_test))

             precision    recall  f1-score   support

          0       0.50      1.00      0.67         1
          1       1.00      0.75      0.86         4

avg / total       0.90      0.80      0.82         5



In [11]:
print(classification_report(pred_rf, y_test))

             precision    recall  f1-score   support

          0       1.00      0.67      0.80         3
          1       0.67      1.00      0.80         2

avg / total       0.87      0.80      0.80         5



In [12]:
print(classification_report(pred_knn, y_test))

             precision    recall  f1-score   support

          0       0.00      0.00      0.00         0
          1       1.00      0.60      0.75         5

avg / total       1.00      0.60      0.75         5



C:\Users\DIU\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1137: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [13]:
print(classification_report(pred_dt, y_test))

             precision    recall  f1-score   support

          0       0.50      1.00      0.67         1
          1       1.00      0.75      0.86         4

avg / total       0.90      0.80      0.82         5



In [14]:
print(confusion_matrix(pred_lr, y_test))

[[1 0]
 [1 3]]


In [15]:
print(confusion_matrix(pred_rf, y_test))

[[2 1]
 [0 2]]


In [16]:
print(confusion_matrix(pred_dt, y_test))

[[1 0]
 [1 3]]


In [17]:
print(confusion_matrix(pred_knn, y_test))

[[0 0]
 [2 3]]
